// Generated by delombok at Fri May 01 02:27:27 IST 2026
package com.ijse.foodorderingsystem.dto;

public class AuthResponse {
    private String token;
    private String type = "Bearer";
    private Long id;
    private String username;
    private String name;
    private String role;

    public AuthResponse(String token, Long id, String username, String name, String role) {
        this.token = token;
        this.id = id;
        this.username = username;
        this.name = name;
        this.role = role;
    }

    
    
    public String getToken() {
        return this.token;
    }

    
    
    public String getType() {
        return this.type;
    }

    
    
    public Long getId() {
        return this.id;
    }

    
    
    public String getUsername() {
        return this.username;
    }

    
    
    public String getName() {
        return this.name;
    }

    
    
    public String getRole() {
        return this.role;
    }

    
    
    public void setToken(final String token) {
        this.token = token;
    }

    
    
    public void setType(final String type) {
        this.type = type;
    }

    
    
    public void setId(final Long id) {
        this.id = id;
    }

    
    
    public void setUsername(final String username) {
        this.username = username;
    }

    
    
    public void setName(final String name) {
        this.name = name;
    }

    
    
    public void setRole(final String role) {
        this.role = role;
    }

    
    
    public AuthResponse(final String token, final String type, final Long id, final String username, final String name, final String role) {
        this.token = token;
        this.type = type;
        this.id = id;
        this.username = username;
        this.name = name;
        this.role = role;
    }
}
