// Generated by delombok at Fri May 01 02:27:27 IST 2026
package com.ijse.foodorderingsystem.dto;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;

public class LoginRequest {
    @NotBlank
    @Email
    private String email;
    @NotBlank
    private String password;

    
    
    public String getEmail() {
        return this.email;
    }

    
    
    public String getPassword() {
        return this.password;
    }

    
    
    public void setEmail(final String email) {
        this.email = email;
    }

    
    
    public void setPassword(final String password) {
        this.password = password;
    }
}
