// Generated by delombok at Fri May 01 02:27:27 IST 2026
package com.ijse.foodorderingsystem.dto;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

public class RegisterRequest {
    @NotBlank
    @Size(min = 3, max = 50)
    private String name;
    @NotBlank
    @Size(max = 50)
    @Email
    private String email;
    @NotBlank
    @Size(min = 6, max = 40)
    private String password;
    private String role; // "ADMIN" or "CUSTOMER" (Defaults to CUSTOMER in controller)

    
    
    public String getName() {
        return this.name;
    }

    
    
    public String getEmail() {
        return this.email;
    }

    
    
    public String getPassword() {
        return this.password;
    }

    
    
    public String getRole() {
        return this.role;
    }

    
    
    public void setName(final String name) {
        this.name = name;
    }

    
    
    public void setEmail(final String email) {
        this.email = email;
    }

    
    
    public void setPassword(final String password) {
        this.password = password;
    }

    
    
    public void setRole(final String role) {
        this.role = role;
    }
}
