// Generated by delombok at Fri May 01 02:27:27 IST 2026
package com.ijse.foodorderingsystem.entity;

import jakarta.persistence.*;

import java.util.List;

@Entity
@Table(name = "carts")
public class Cart {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @OneToOne
    @JoinColumn(name = "user_id")
    private User user;
    @OneToMany(mappedBy = "cart", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<CartItem> cartItems;

    
    
    public Long getId() {
        return this.id;
    }

    
    
    public User getUser() {
        return this.user;
    }

    
    
    public List<CartItem> getCartItems() {
        return this.cartItems;
    }

    
    
    public void setId(final Long id) {
        this.id = id;
    }

    
    
    public void setUser(final User user) {
        this.user = user;
    }

    
    
    public void setCartItems(final List<CartItem> cartItems) {
        this.cartItems = cartItems;
    }

    
    
    public Cart() {
    }

    
    
    public Cart(final Long id, final User user, final List<CartItem> cartItems) {
        this.id = id;
        this.user = user;
        this.cartItems = cartItems;
    }
}
