// Generated by delombok at Fri May 01 02:27:27 IST 2026
package com.ijse.foodorderingsystem.entity;

import jakarta.persistence.*;


@Entity
@Table(name = "cart_items")
public class CartItem {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private Integer quantity;
    @ManyToOne
    @JoinColumn(name = "cart_id")
    private Cart cart;
    @ManyToOne
    @JoinColumn(name = "food_item_id")
    private FoodItem foodItem;

    
    
    public Long getId() {
        return this.id;
    }

    
    
    public Integer getQuantity() {
        return this.quantity;
    }

    
    
    public Cart getCart() {
        return this.cart;
    }

    
    
    public FoodItem getFoodItem() {
        return this.foodItem;
    }

    
    
    public void setId(final Long id) {
        this.id = id;
    }

    
    
    public void setQuantity(final Integer quantity) {
        this.quantity = quantity;
    }

    
    
    public void setCart(final Cart cart) {
        this.cart = cart;
    }

    
    
    public void setFoodItem(final FoodItem foodItem) {
        this.foodItem = foodItem;
    }

    
    
    public CartItem() {
    }

    
    
    public CartItem(final Long id, final Integer quantity, final Cart cart, final FoodItem foodItem) {
        this.id = id;
        this.quantity = quantity;
        this.cart = cart;
        this.foodItem = foodItem;
    }
}
