// Generated by delombok at Fri May 01 02:27:27 IST 2026
package com.ijse.foodorderingsystem.entity;

import jakarta.persistence.*;

import java.util.List;

@Entity
@Table(name = "categories")
public class Category {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String name;
    private String description;
    @OneToMany(mappedBy = "category", cascade = CascadeType.ALL)
    private List<FoodItem> foodItems;

    
    
    public Long getId() {
        return this.id;
    }

    
    
    public String getName() {
        return this.name;
    }

    
    
    public String getDescription() {
        return this.description;
    }

    
    
    public List<FoodItem> getFoodItems() {
        return this.foodItems;
    }

    
    
    public void setId(final Long id) {
        this.id = id;
    }

    
    
    public void setName(final String name) {
        this.name = name;
    }

    
    
    public void setDescription(final String description) {
        this.description = description;
    }

    
    
    public void setFoodItems(final List<FoodItem> foodItems) {
        this.foodItems = foodItems;
    }

    
    
    public Category() {
    }

    
    
    public Category(final Long id, final String name, final String description, final List<FoodItem> foodItems) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.foodItems = foodItems;
    }
}
