// Generated by delombok at Fri May 01 02:27:27 IST 2026
package com.ijse.foodorderingsystem.entity;

import jakarta.persistence.*;

import java.math.BigDecimal;

@Entity
@Table(name = "food_items")
public class FoodItem {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String name;
    private String description;
    private BigDecimal price;
    private String imageUrl;
    @Enumerated(EnumType.STRING)
    private Status status;
    @ManyToOne
    @JoinColumn(name = "category_id")
    private Category category;


    public enum Status {
        AVAILABLE, OUT_OF_STOCK;
    }

    
    
    public Long getId() {
        return this.id;
    }

    
    
    public String getName() {
        return this.name;
    }

    
    
    public String getDescription() {
        return this.description;
    }

    
    
    public BigDecimal getPrice() {
        return this.price;
    }

    
    
    public String getImageUrl() {
        return this.imageUrl;
    }

    
    
    public Status getStatus() {
        return this.status;
    }

    
    
    public Category getCategory() {
        return this.category;
    }

    
    
    public void setId(final Long id) {
        this.id = id;
    }

    
    
    public void setName(final String name) {
        this.name = name;
    }

    
    
    public void setDescription(final String description) {
        this.description = description;
    }

    
    
    public void setPrice(final BigDecimal price) {
        this.price = price;
    }

    
    
    public void setImageUrl(final String imageUrl) {
        this.imageUrl = imageUrl;
    }

    
    
    public void setStatus(final Status status) {
        this.status = status;
    }

    
    
    public void setCategory(final Category category) {
        this.category = category;
    }

    
    
    public FoodItem() {
    }

    
    
    public FoodItem(final Long id, final String name, final String description, final BigDecimal price, final String imageUrl, final Status status, final Category category) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.price = price;
        this.imageUrl = imageUrl;
        this.status = status;
        this.category = category;
    }
}
