// Generated by delombok at Fri May 01 02:27:27 IST 2026
package com.ijse.foodorderingsystem.entity;

import jakarta.persistence.*;

import java.math.BigDecimal;

@Entity
@Table(name = "order_items")
public class OrderItem {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private Integer quantity;
    private BigDecimal price; // Price at the time of order
    @ManyToOne
    @JoinColumn(name = "order_id")
    private Order order;
    @ManyToOne
    @JoinColumn(name = "food_item_id")
    private FoodItem foodItem;

    
    
    public Long getId() {
        return this.id;
    }

    
    
    public Integer getQuantity() {
        return this.quantity;
    }

    
    
    public BigDecimal getPrice() {
        return this.price;
    }

    
    
    public Order getOrder() {
        return this.order;
    }

    
    
    public FoodItem getFoodItem() {
        return this.foodItem;
    }

    
    
    public void setId(final Long id) {
        this.id = id;
    }

    
    
    public void setQuantity(final Integer quantity) {
        this.quantity = quantity;
    }

    
    
    public void setPrice(final BigDecimal price) {
        this.price = price;
    }

    
    
    public void setOrder(final Order order) {
        this.order = order;
    }

    
    
    public void setFoodItem(final FoodItem foodItem) {
        this.foodItem = foodItem;
    }

    
    
    public OrderItem() {
    }

    
    
    public OrderItem(final Long id, final Integer quantity, final BigDecimal price, final Order order, final FoodItem foodItem) {
        this.id = id;
        this.quantity = quantity;
        this.price = price;
        this.order = order;
        this.foodItem = foodItem;
    }
}
