// Generated by delombok at Fri May 01 02:27:27 IST 2026
package com.ijse.foodorderingsystem.entity;

import jakarta.persistence.*;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

@Entity
@Table(name = "orders")
public class Order {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private LocalDateTime orderDate;
    private BigDecimal totalAmount;
    @Enumerated(EnumType.STRING)
    private Status status;
    @ManyToOne
    @JoinColumn(name = "user_id")
    private User user;
    @OneToMany(mappedBy = "order", cascade = CascadeType.ALL)
    private List<OrderItem> orderItems;
    @OneToOne(mappedBy = "order", cascade = CascadeType.ALL)
    private Payment payment;


    public enum Status {
        PLACED, PREPARING, DELIVERED, CANCELLED;
    }

    
    
    public Long getId() {
        return this.id;
    }

    
    
    public LocalDateTime getOrderDate() {
        return this.orderDate;
    }

    
    
    public BigDecimal getTotalAmount() {
        return this.totalAmount;
    }

    
    
    public Status getStatus() {
        return this.status;
    }

    
    
    public User getUser() {
        return this.user;
    }

    
    
    public List<OrderItem> getOrderItems() {
        return this.orderItems;
    }

    
    
    public Payment getPayment() {
        return this.payment;
    }

    
    
    public void setId(final Long id) {
        this.id = id;
    }

    
    
    public void setOrderDate(final LocalDateTime orderDate) {
        this.orderDate = orderDate;
    }

    
    
    public void setTotalAmount(final BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    
    
    public void setStatus(final Status status) {
        this.status = status;
    }

    
    
    public void setUser(final User user) {
        this.user = user;
    }

    
    
    public void setOrderItems(final List<OrderItem> orderItems) {
        this.orderItems = orderItems;
    }

    
    
    public void setPayment(final Payment payment) {
        this.payment = payment;
    }

    
    
    public Order() {
    }

    
    
    public Order(final Long id, final LocalDateTime orderDate, final BigDecimal totalAmount, final Status status, final User user, final List<OrderItem> orderItems, final Payment payment) {
        this.id = id;
        this.orderDate = orderDate;
        this.totalAmount = totalAmount;
        this.status = status;
        this.user = user;
        this.orderItems = orderItems;
        this.payment = payment;
    }
}
