// Generated by delombok at Fri May 01 02:27:27 IST 2026
package com.ijse.foodorderingsystem.entity;

import jakarta.persistence.*;

import java.math.BigDecimal;
import java.time.LocalDateTime;

@Entity
@Table(name = "payments")
public class Payment {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private BigDecimal amount;
    private String paymentMethod;
    private LocalDateTime paymentDate;
    @Enumerated(EnumType.STRING)
    private Status status;
    @OneToOne
    @JoinColumn(name = "order_id")
    private Order order;


    public enum Status {
        PENDING, COMPLETED, FAILED;
    }

    
    
    public Long getId() {
        return this.id;
    }

    
    
    public BigDecimal getAmount() {
        return this.amount;
    }

    
    
    public String getPaymentMethod() {
        return this.paymentMethod;
    }

    
    
    public LocalDateTime getPaymentDate() {
        return this.paymentDate;
    }

    
    
    public Status getStatus() {
        return this.status;
    }

    
    
    public Order getOrder() {
        return this.order;
    }

    
    
    public void setId(final Long id) {
        this.id = id;
    }

    
    
    public void setAmount(final BigDecimal amount) {
        this.amount = amount;
    }

    
    
    public void setPaymentMethod(final String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    
    
    public void setPaymentDate(final LocalDateTime paymentDate) {
        this.paymentDate = paymentDate;
    }

    
    
    public void setStatus(final Status status) {
        this.status = status;
    }

    
    
    public void setOrder(final Order order) {
        this.order = order;
    }

    
    
    public Payment() {
    }

    
    
    public Payment(final Long id, final BigDecimal amount, final String paymentMethod, final LocalDateTime paymentDate, final Status status, final Order order) {
        this.id = id;
        this.amount = amount;
        this.paymentMethod = paymentMethod;
        this.paymentDate = paymentDate;
        this.status = status;
        this.order = order;
    }
}
