// Generated by delombok at Fri May 01 02:27:27 IST 2026
package com.ijse.foodorderingsystem.entity;

import jakarta.persistence.*;


@Entity
@Table(name = "users")
public class User {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String name;
    @Column(unique = true)
    private String email;
    private String password;
    @Enumerated(EnumType.STRING)
    private Role role;


    public enum Role {
        ADMIN, CUSTOMER;
    }

    
    
    public Long getId() {
        return this.id;
    }

    
    
    public String getName() {
        return this.name;
    }

    
    
    public String getEmail() {
        return this.email;
    }

    
    
    public String getPassword() {
        return this.password;
    }

    
    
    public Role getRole() {
        return this.role;
    }

    
    
    public void setId(final Long id) {
        this.id = id;
    }

    
    
    public void setName(final String name) {
        this.name = name;
    }

    
    
    public void setEmail(final String email) {
        this.email = email;
    }

    
    
    public void setPassword(final String password) {
        this.password = password;
    }

    
    
    public void setRole(final Role role) {
        this.role = role;
    }

    
    
    public User() {
    }

    
    
    public User(final Long id, final String name, final String email, final String password, final Role role) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.password = password;
        this.role = role;
    }
}
